---
- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"

- name: ensure tmux is installed
  package:
    name: "{{ item }}"
  with_items:
    - git
    - tmux

- name: ensure powerline for tmux is installed
  package:
    name: tmux-powerline
  when: tmux_powerline and ansible_os_family == 'RedHat'

- name: get version of tmux
  shell: "tmux -V | cut -d' ' -f2"
  register: tmux_version
  changed_when: false

- include: config.yml
